### ISSUE TITLE
Gitignore file incomplete

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet-code-samples#12]
It doesn't exclude "`.checkstyle`" files, so the repo contains more than it should.

**Comment by viliam-durina** [comment]
I don't have any `.checkstyle` file in this repo?

**Comment by neilstevenson** [comment]
It did in a fork but these were deleted.

In a sense, this is related to https://github.com/hazelcast/hazelcast-jet/issues/356

The `.gitignore` file is different on `hazelcast` `hazelcast-jet` and `hazelcast-jet-code-samples`
