### ISSUE TITLE
Problems and warnings with hazelcast-jet-code-samples in Eclipse

### ISSUE THREAD

**Issue by Raichelloca** [hazelcast/hazelcast-jet-code-samples#13]
Hi.
I downloaded and opened hazelcast jet samples in my Eclipse (with Windows) and I found the next problems and warnings:

![image](https://cloud.githubusercontent.com/assets/26595043/24190166/0e8b6fa8-0ee8-11e7-9ad9-5027fa9d8cf4.png)

However, when I try to run each samples I find that it runs correctly:

![image](https://cloud.githubusercontent.com/assets/26595043/24190397/dad7ac02-0ee8-11e7-8ca7-8a592763f368.png)

Could you tell me something about the errors, please?
Thank you.

**Comment by viliam-durina** [comment]
It's a bug in eclipse compiler: http://stackoverflow.com/a/41571931/952135. I'll push a workaround.
