### ISSUE TITLE
Checkstyle exception in refman module with mvn clean install 

### ISSUE THREAD

**Issue by hiteshpanchani** [hazelcast/hazelcast-jet-code-samples#77]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] hazelcast-jet-code-samples ......................... SUCCESS [  1.354 s]
[INFO] batch .............................................. SUCCESS [  0.028 s]
[INFO] access-log-analyzer ................................ SUCCESS [  1.942 s]
[INFO] co-group ........................................... SUCCESS [  0.606 s]
[INFO] sample-data ........................................ SUCCESS [  0.495 s]
[INFO] java.util.stream ................................... SUCCESS [  1.048 s]
[INFO] hazelcast-connectors ............................... SUCCESS [  0.494 s]
[INFO] wordcount .......................................... SUCCESS [  0.397 s]
[INFO] wordcount-hadoop ................................... SUCCESS [  0.440 s]
[INFO] samples-core-api ................................... SUCCESS [  0.023 s]
[INFO] core-api-batch ..................................... SUCCESS [  0.019 s]
[INFO] map-dump ........................................... SUCCESS [  0.397 s]
[INFO] mapreduce-migration ................................ SUCCESS [  0.419 s]
[INFO] prime-finder ....................................... SUCCESS [  0.425 s]
[INFO] tf-idf ............................................. SUCCESS [  0.393 s]
[INFO] wordcount-core-api ................................. SUCCESS [  0.366 s]
[INFO] enrichment-core-api ................................ SUCCESS [  0.448 s]
[INFO] core-api-streaming ................................. SUCCESS [  0.017 s]
[INFO] access-stream-analyzer ............................. SUCCESS [  0.373 s]
[INFO] fault-tolerance .................................... SUCCESS [  0.617 s]
[INFO] session-windows .................................... SUCCESS [  1.183 s]
[INFO] trade-generator .................................... SUCCESS [  0.976 s]
[INFO] stock-exchange ..................................... SUCCESS [  1.016 s]
[INFO] top-n-stocks ....................................... SUCCESS [  0.975 s]
[INFO] pcf ................................................ SUCCESS [  2.761 s]
[INFO] refman ............................................. FAILURE [  1.100 s]
[INFO] streaming .......................................... SKIPPED
[INFO] enrichment ......................................... SKIPPED
[INFO] map-journal-source ................................. SKIPPED
[INFO] kafka-source ....................................... SKIPPED
[INFO] socket-connector ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.027 s
[INFO] Finished at: 2017-11-30T16:58:29-06:00
[INFO] Final Memory: 37M/601M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:checkstyle (default) on project refman: An error has occurred in Checkstyle report generation.: Failed during checkstyle execution: There are 2 errors reported by Checkstyle 6.11.2 with /hazelcast\examples/checkstyle/checkstyle.xml ruleset. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

![image](https://user-images.githubusercontent.com/8516821/33460443-baf02572-d5f3-11e7-9c0a-e3c27b140d5b.png)

**Comment by viliam-durina** [comment]
The build works for me with `mvn clean install` command. What command did you execute? 
Could you also share your environment (JDK version, OS)? Are you building from current `master` branch or some other?

**Comment by cangencer** [comment]
The failure was on `0.5-maintenance` branch, it should be building fine now.

**Comment by hiteshpanchani** [comment]
Thanks, Can. Much appreciated.
